export const operationalAreaAliases = {
  cadastros: ["cadastro", "cadastros", "clientes", "leads", "produtos", "servicos", "serviços"],
  operacoes: ["operacoes", "operações", "projetos", "ordens", "processos"],
  vendas: ["vendas", "propostas", "negociacoes", "negociações", "funil"],
  financeiro: ["financeiro", "ganhos", "gastos", "despesas", "receitas", "fluxo de caixa", "caixa"],
  equipe: ["equipe", "comercial", "operacional", "administrativo", "financeiro", "membros"],
  documentos: ["documentos", "contratos", "arquivos", "relatorios", "relatórios"],
  reunioes: ["reunioes", "reuniões", "reuniao", "reunião", "meet"],
  suporte: ["suporte", "chamados", "duvidas", "dúvidas", "problemas", "cobranca", "cobrança", "integracoes", "integrações"],
  sistema: ["sistema", "logs", "alertas", "configuracoes", "configurações", "integracoes", "integrações"],
} as const

export const operationalEntityAliases = {
  client: ["cliente", "clientes"],
  lead: ["lead", "leads"],
  product: ["produto", "produtos"],
  service: ["servico", "serviço", "servicos", "serviços"],
  project: ["projeto", "projetos"],
  order: ["ordem", "ordem de servico", "ordem de serviço", "ordens"],
  process: ["processo", "processos", "onboarding"],
  proposal: ["proposta", "propostas"],
  negotiation: ["negociacao", "negociação", "negociacoes", "negociações", "funil"],
  task: ["tarefa", "tarefas", "to-do", "todo"],
  income: ["ganho", "ganhos", "receita", "receitas", "entrada", "entradas", "faturamento", "venda", "vendas"],
  expense: ["gasto", "gastos", "despesa", "despesas", "conta", "contas"],
  cash_flow: ["fluxo de caixa", "caixa", "saldo", "balanco", "balanço"],
  member: ["membro", "membros", "equipe", "colaborador", "colaboradores"],
  document: ["documento", "documentos"],
  contract: ["contrato", "contratos"],
  file: ["arquivo", "arquivos"],
  form: ["formulario", "formulário", "formularios", "formulários"],
  report: ["relatorio", "relatório", "relatorios", "relatórios"],
  meeting: ["reuniao", "reunião", "reunioes", "reuniões", "meet"],
  ticket: ["chamado", "chamados", "suporte", "ticket", "tickets"],
  system_log: ["log", "logs", "alerta", "alertas"],
  integration: ["integracao", "integração", "integracoes", "integrações"],
  marketing_action: ["marketing", "campanha", "campanhas", "acao de marketing", "ação de marketing"],
} as const

export const operationalReferenceAliases = [
  "dele",
  "dela",
  "nele",
  "nela",
  "esse",
  "essa",
  "este",
  "esta",
  "aquele",
  "aquela",
  "o mesmo",
  "a mesma",
  "esse cliente",
  "essa cliente",
  "esse gasto",
  "essa entrada",
  "esse projeto",
  "esse documento",
  "esse chamado",
  "essa reuniao",
  "essa reunião",
  "ultimo cliente",
  "último cliente",
  "ultimo gasto",
  "último gasto",
  "ultima entrada",
  "última entrada",
  "ultimo projeto",
  "último projeto",
  "ultimo chamado",
  "último chamado",
  "ultimo documento",
  "último documento",
  "ultima reuniao",
  "última reunião",
] as const
